from typing import Literal

# Default node dimensions (width, height) matching Unity prefabs - for full serialization format
NODE_SIZES = {
    "String": (256, 64),
    "Float": (256, 64),
    "Color": (256, 64),
    "Country": (256, 64),
    "Bool": (256, 64),
    "ModularCarController": (192, 160),
    "UniformModularCarProperties": (192, 288),
    "Spherecast": (256, 64),
    "CarRaycasts": (192, 160),
    "HitInfo": (256, 64),
    "ParkingGetFloat": (320, 64),
    "ParkingGetBool": (320, 64),
    "ParkingGetTransform": (320, 64),
    "DemoDerbyGetTransform": (320, 64),
    "DemoDerbyGetCar": (320, 64),
    "GetCarPart": (320, 64),
    "CarInfo": (192, 224),
    "Autosteer": (192, 160),
    "Autothrottle": (192, 160),
    "GetCarFromTransform": (256, 64),
    "ConstructSurvivalProperties": (192, 288),
    "ConstructVector3": (256, 160),
    "CompareFloats": (256, 160),
    "CompareBool": (256, 160),
    "SurvivalGetFloat": (320, 64),
    "SurvivalGetBool": (320, 64),
    "SurvivalState": (256, 64),
    "ConditionalSetSurvivalState": (256, 288),
    "ConditionalSetSurvivalEmote": (256, 288),
    "SurvivalAutoPosition": (256, 64),
    "SurvivalEmote": (256, 64),
    "SurvivalController": (192, 160),
    "Relay": (32, 32),
    "AddFloats": (256, 64),
    "SubtractFloats": (256, 64),
    "MultiplyFloats": (256, 64),
    "DivideFloats": (256, 64),
    "Not": (256, 64),
    "Modulo": (256, 64),
    "Operation": (256, 64),
    "Power": (256, 64),
    "Lerp": (256, 96),
    "GetVariable": (256, 64),
    "SetVariable": (256, 64),
    "IsNull": (256, 64),
    "Region": (256, 224),
    "CreateFunction": (400, 332),
    "Function": (256, 160),
    "SoccerController1": (192, 160),
    "SoccerController2": (192, 160),
    "SoccerController3": (192, 160),
    "SoccerController4": (192, 160),
    "SoccerPlayerSensors1": (192, 224),
    "SoccerPlayerSensors2": (192, 224),
    "SoccerPlayerSensors3": (192, 224),
    "SoccerPlayerSensors4": (192, 224),
    "ConstructSoccerProperties": (192, 224),
    "SoccerGetBool": (320, 64),
    "SoccerGetFloat": (320, 64),
    "SoccerGetTransform": (320, 64),
    "SoccerGetVector3": (320, 64),
    "RacingV2GetFloat": (320, 64),
    "RacingV2GetBool": (320, 64),
    "RacingV2GetCar": (320, 64),
    "RacingV2GetWaypoint": (320, 64),
    "RacingV2Waypoint": (256, 96),
    "ConstructRacingV2Properties": (192, 320),
}
DEFAULT_NODE_SIZE = (256, 64)

# Node types that serialize size/color per NodeTypeDataSO (e.g. Region has user-resizable dimensions)
SERIALIZE_SIZE_DELTA_NODES = {"Region", "CreateFunction"}
SERIALIZE_COLOR_NODES = {"Region"}

# Default colors matching Unity (RGBA 0-1)
DEFAULT_NODE_COLOR = {"r": 0.21960784494876862, "g": 0.21960784494876862, "b": 0.21960784494876862, "a": 1}
DEFAULT_CONNECTION_COLOR = {"r": 0.98, "g": 0.94, "b": 0.84, "a": 1}
CAP_COLOR = {"r": 1, "g": 0.81, "b": 0.3, "a": 1}

# Dropdown / selection modifier options for nodes whose `modifier` field
# represents a Unity dropdown selection index. Keys are node IDs.
# Values are ordered display labels (index = dropdown value).
#
# This is used by the Python "compiler" (SaveData JSON serializer) to:
# - validate user-provided string selections
# - convert them to the correct dropdown index expected by Unity nodes
DROPDOWN_OPTIONS: dict[str, tuple[str, ...]] = {
    # Parking simulation
    "ParkingGetTransform": ("Self", "Target Parking Stall"),
    "ParkingGetBool": (
        "Is Partially in Target Parking Stall",
        "Is Fully in Target Parking Stall",
    ),
    "ParkingGetFloat": (
        "Speed",
        "Distance to Stall (based on pathfinding)",
        "Target Stall Width",
        "Target Stall Depth",
        "Current Level",
        "Fail Count",
        "Current Simulation Time",
        "Max Simulation Time",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
        "Signed Speed (forward +, reverse −)",
    ),
    # RacingV2 simulation
    "RacingV2GetFloat": (
        "Speed",
        "Signed Speed (forward +, reverse −)",
        "Index of next waypoint",
        "Index of previous waypoint",
        "Waypoint count",
        "Current race rank",
        "Number of competitors",
        "Distance to next waypoint",
        "Distance to previous waypoint",
        "Current lap time",
        "Best lap time",
        "Total race time",
        "Current lap",
        "Total laps",
        "Current Simulation Time",
        "Max Simulation Time",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
    ),
    "RacingV2GetBool": (
        "Is Grounded",
        "Is Disabled",
        "Simulation started",
    ),
    "RacingV2GetCar": (
        "By index",
        "By rank",
        "Self",
        "Nearest car",
        "Furthest car",
        "Lowest health car",
        "Highest health car",
        "Last damaged car",
        "Nearest active car",
        "Furthest active car",
        "Nearest disabled car",
        "Furthest disabled car",
        "Nearest car with disabled steering",
        "Furthest car with disabled steering",
        "Nearest AI-Authored",
        "Lowest health AI-Authored",
        "Highest health AI-Authored",
        "Nearest Human-Authored",
        "Lowest health Human-Authored",
        "Highest health Human-Authored",
        "Highest ranked car",
        "Lowest ranked car",
        "Nearest ranked car (rank neighbor)",
        "Highest ranked (not immobilized)",
        "Highest ranked (immobilized)",
        "Lowest ranked (not immobilized)",
        "Lowest ranked (immobilized)",
    ),
    "RacingV2GetWaypoint": (
        "Next waypoint",
        "Previous waypoint",
        "By index",
        "Start waypoint",
    ),
    "RacingV2Waypoint": (
        "Center",
        "Left",
        "Right",
        "Nearest point",
    ),
    # Soccer simulation
    "SoccerGetBool": (
        "Team Has Ball",
        "Opponent Has Ball",
        "Is Ball Loose",
        "Team Player 1 Has Ball",
        "Team Player 2 Has Ball",
        "Team Player 3 Has Ball",
        "Team Player 4 Has Ball",
        "Opponent Player 1 Has Ball",
        "Opponent Player 2 Has Ball",
        "Opponent Player 3 Has Ball",
        "Opponent Player 4 Has Ball",
        "Is Ball Nearby Team Player 1",
        "Is Ball Nearby Team Player 2",
        "Is Ball Nearby Team Player 3",
        "Is Ball Nearby Team Player 4",
        "Is Ball Nearby Opponent Player 1",
        "Is Ball Nearby Opponent Player 2",
        "Is Ball Nearby Opponent Player 3",
        "Is Ball Nearby Opponent Player 4",
        "Is Team Player 1 Closest Teammate to Ball",
        "Is Team Player 2 Closest Teammate to Ball",
        "Is Team Player 3 Closest Teammate to Ball",
        "Is Team Player 4 Closest Teammate to Ball",
        "Is Opponent Player 1 Closest Opponent to Ball",
        "Is Opponent Player 2 Closest Opponent to Ball",
        "Is Opponent Player 3 Closest Opponent to Ball",
        "Is Opponent Player 4 Closest Opponent to Ball",
        "Is Team Player 1 Open",
        "Is Team Player 2 Open",
        "Is Team Player 3 Open",
        "Is Team Player 4 Open",
        "Is Opponent Player 1 Open",
        "Is Opponent Player 2 Open",
        "Is Opponent Player 3 Open",
        "Is Opponent Player 4 Open",
        "Is Kickoff",
        "Is Team Kicking off",
        "Is Opponent Kicking off",
        "Team Is Winning",
        "Opponent Is Winning",
        "Team Scored Last Point",
        "Opponent Scored Last Point",
        "Ball On Team Side",
        "Ball On Opponent Side",
        "Is Ball Headed Towards Team Goal",
        "Is Ball Headed Towards Opponent Goal",
        "Is Home Team",
        "Is Away Team",
        "Is Active Graph",
    ),
    "SoccerGetFloat": (
        "Team Score",
        "Opponent Score",
        "Team Shots",
        "Opponent Shots",
        "Team Possession %",
        "Opponent Possession %",
        "Team Attacking %",
        "Opponent Attacking %",
        "Ball Speed",
        "Player Interact Radius",
        "Ball Carrier Stamina",
        "Ball Carrier Shot Charge",
        "Teammate 1 Shot Charge",
        "Teammate 2 Shot Charge",
        "Teammate 3 Shot Charge",
        "Teammate 4 Shot Charge",
        "Field Width",
        "Field Depth",
        "Kickoff Circle Radius",
        "Goal Width",
        "Goal Height",
        "Team Player 1 Stamina",
        "Team Player 2 Stamina",
        "Team Player 3 Stamina",
        "Team Player 4 Stamina",
        "Distance from Team Player 1 to nearest Opponent",
        "Distance from Team Player 2 to nearest Opponent",
        "Distance from Team Player 3 to nearest Opponent",
        "Distance from Team Player 4 to nearest Opponent",
        "Opponent Player 1 Stamina",
        "Opponent Player 2 Stamina",
        "Opponent Player 3 Stamina",
        "Opponent Player 4 Stamina",
        "Opponent Nearest Teammate Player 1 Stamina",
        "Opponent Nearest Teammate Player 2 Stamina",
        "Opponent Nearest Teammate Player 3 Stamina",
        "Opponent Nearest Teammate Player 4 Stamina",
        "Stamina of last defending opponent",
        "Current Simulation Time",
        "Max Simulation Time",
        "Simulation Time Remaining",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
    ),
    "SoccerGetTransform": (
        "Ball",
        "Team Player 1",
        "Team Player 2",
        "Team Player 3",
        "Team Player 4",
        "Opponent Player 1",
        "Opponent Player 2",
        "Opponent Player 3",
        "Opponent Player 4",
        "Teammate Nearest Team Player 1",
        "Teammate Nearest Team Player 2",
        "Teammate Nearest Team Player 3",
        "Teammate Nearest Team Player 4",
        "Opponent Nearest Team Player 1",
        "Opponent Nearest Team Player 2",
        "Opponent Nearest Team Player 3",
        "Opponent Nearest Team Player 4",
        "Team Goal Center",
        "Team Goal Left Post",
        "Team Goal Right Post",
        "Opponent Goal Center",
        "Opponent Goal Left Post",
        "Opponent Goal Right Post",
        "Opponent Nearest Team Goal",
        "Opponent Nearest Opponent Goal",
        "Teammate Nearest Team Goal",
        "Teammate Nearest Opponent Goal",
    ),
    "SoccerGetVector3": (
        "Ball Velocity",
        "Clear direction from team carrier",
        "Backwards clear direction from team carrier",
        "Clear direction from team carrier (avoid goal lines)",
        "Clear direction from team carrier (avoid sidelines)",
        "Clear direction from team carrier (avoid all walls)",
        "Upper Corner Home Side",
        "Lower Corner Home Side",
        "Upper Midfield",
        "Lower Midfield",
        "Upper Corner Away Side",
        "Lower Corner Away Side",
        "Upper Corner Opposing Side",
        "Lower Corner Opposing Side",
        "Upper Corner Team Side",
        "Lower Corner Team Side",
        "Center Field",
        "Get nearest open teammate",
        "Get furthest open teammate",
        "Get most open teammate",
        "Get nearest open opponent",
        "Get furthest open opponent",
        "Get most open opponent",
        "Direction of clear teammate from Teammate 1",
        "Direction of clear teammate from Teammate 2",
        "Direction of clear teammate from Teammate 3",
        "Direction of clear teammate from Teammate 4",
        "Direction of clear teammate from Opponent 1",
        "Direction of clear teammate from Opponent 2",
        "Direction of clear teammate from Opponent 3",
        "Direction of clear teammate from Opponent 4",
        "Direction of ball from Teammate 1",
        "Direction of ball from Teammate 2",
        "Direction of ball from Teammate 3",
        "Direction of ball from Teammate 4",
        "Direction of ball from Opponent 1",
        "Direction of ball from Opponent 2",
        "Direction of ball from Opponent 3",
        "Direction of ball from Opponent 4",
        "Direction of team goal from Teammate 1",
        "Direction of team goal from Teammate 2",
        "Direction of team goal from Teammate 3",
        "Direction of team goal from Teammate 4",
        "Direction of opponent goal from Teammate 1",
        "Direction of opponent goal from Teammate 2",
        "Direction of opponent goal from Teammate 3",
        "Direction of opponent goal from Teammate 4",
        "Clear direction from Teammate 1",
        "Clear direction from Teammate 2",
        "Clear direction from Teammate 3",
        "Clear direction from Teammate 4",
        "Direction of teammate from Team Player 1",
        "Direction of teammate from Team Player 2",
        "Direction of teammate from Team Player 3",
        "Direction of teammate from Team Player 4",
    ),
}

outputs = {
    "AddVector3": "Vector3",
    "AddFloats": float,
    "Bool": bool,
    "ClampFloat": float,
    "Color": float,
    "UniformModularCarProperties": None,
    "ModularCarController": None,
    "ConstructVector3": "Vector3",
    "CompareBool": bool,
    "CompareFloats": bool,
    "ConditionalSetFloatV2": float,
    "ConditionalSetVector3": "Vector3",
    "ConstructSlimeProperties": None,
    "SlimeController": None,
    "Spherecast": "Spherecast",
    "CarRaycasts": "RaycastHit",
    "HitInfo": "Any",
    "Country": "Country",
    "CrossProduct": "Vector3",
    "Debug": None,
    "DebugDrawLine": None,
    "DebugDrawDisc": None,
    "Distance": float,
    "DivideFloats": float,
    "DotProduct": float,
    "Float": float,
    "VolleyballGetBool": bool,
    "VolleyballGetFloat": float,
    "VolleyballGetTransform": "Transform",
    "SlimeGetVector3": "Vector3",
    "Magnitude": float,
    "Modulo": float,
    "MultiplyFloats": float,
    "Not": bool,
    "Normalize": "Vector3",
    "Operation": float,
    "Power": float,
    "Lerp": float,
    "RelativePosition": "Vector3",
    "RandomFloat": float,
    "ScaleVector3": "Vector3",
    "Vector3Split": float,
    "Stat": "Stat",
    "String": str,
    "SubtractFloats": float,
    "SubtractVector3": "Vector3",
    "ConditionalSetBool": bool,
    "ConditionalSetSurvivalEmote": "SurvivalEmote",
    "ConditionalSetSurvivalState": "SurvivalState",
    "ConstructSurvivalProperties": None,
    "GetVariable": "Any",
    "IsNull": bool,
    "Keypress": bool,
    "Region": None,
    "Relay": "Any",
    "SetVariable": None,
    "SurvivalAutoPosition": "Vector3",
    "SurvivalController": None,
    "SurvivalEmote": "SurvivalEmote",
    "SurvivalGetBool": bool,
    "SurvivalGetFloat": float,
    "SurvivalGetTransform": "Transform",
    "SurvivalState": "SurvivalState",
    "TimePlot": None,
    "ParkingGetFloat": float,
    "ParkingGetBool": bool,
    "ParkingGetTransform": "Transform",
    "DemoDerbyGetTransform": "Transform",
    "DemoDerbyGetCar": "Car",
    "GetCarPart": "Transform",
    "CarInfo": "Vector3",
    "Autosteer": float,
    "Autothrottle": float,
    "GetCarFromTransform": "Car",
    "CreateFunction": "Any",
    "Function": "Any",
    "SoccerController1": None,
    "SoccerController2": None,
    "SoccerController3": None,
    "SoccerController4": None,
    "SoccerPlayerSensors1": "RaycastHit",
    "SoccerPlayerSensors2": "RaycastHit",
    "SoccerPlayerSensors3": "RaycastHit",
    "SoccerPlayerSensors4": "RaycastHit",
    "ConstructSoccerProperties": None,
    "SoccerGetBool": bool,
    "SoccerGetFloat": float,
    "SoccerGetTransform": "Transform",
    "SoccerGetVector3": "Vector3",
    "RacingV2GetFloat": float,
    "RacingV2GetBool": bool,
    "RacingV2GetCar": "Car",
    "RacingV2GetWaypoint": "Waypoint",
    "RacingV2Waypoint": "Vector3",
    "ConstructRacingV2Properties": None,
}

ports = {
    "AddVector3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "AddFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Bool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "ClampFloat": [
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Color": [
        {"id": "Color1", "polarity": 1}
    ],
    "ConstructVector3": [
        {"id": "Vector31", "polarity": 1},
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "CompareBool": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool2", "polarity": 0},
        {"id": "Bool1", "polarity": 0}
    ],
    "CompareFloats": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "ConditionalSetFloatV2": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Bool1", "polarity": 0}
    ],
    "ConditionalSetVector3": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "ConstructSlimeProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Stat1", "polarity": 0},
        {"id": "Stat2", "polarity": 0},
        {"id": "Stat3", "polarity": 0}
    ],
    "SlimeController": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Vector31", "polarity": 0}
    ],
    "Country": [
        {"id": "Country1", "polarity": 1}
    ],
    "CrossProduct": [
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector3", "polarity": 1}
    ],
    "Debug": [
        {"id": "Any1", "polarity": 0}
    ],
    "DebugDrawLine": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Color1", "polarity": 0}
    ],
    "DebugDrawDisc": [
        {"id": "Float1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "Distance": [
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Vector31", "polarity": 0}
    ],
    "DivideFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "DotProduct": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "Float": [
        {"id": "Float1", "polarity": 1}
    ],
    "VolleyballGetBool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "VolleyballGetFloat": [
        {"id": "Float1", "polarity": 1}
    ],
    "VolleyballGetTransform": [
        {"id": "Transform1", "polarity": 1}
    ],
    "SlimeGetVector3": [
        {"id": "Vector31", "polarity": 1}
    ],
    "Magnitude": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "Modulo": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "MultiplyFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Not": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool1", "polarity": 0}
    ],
    "Normalize": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "Operation": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float1", "polarity": 0}
    ],
    "Power": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "Lerp": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "RelativePosition": [
        {"id": "Transform1", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "RandomFloat": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0}
    ],
    "ScaleVector3": [
        {"id": "Float1", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Vector31", "polarity": 0}
    ],
    "Vector3Split": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 1},
        {"id": "Float3", "polarity": 1}
    ],
    "Stat": [
        {"id": "Stat1", "polarity": 1}
    ],
    "String": [
        {"id": "String1", "polarity": 1}
    ],
    "SubtractFloats": [
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "SubtractVector3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Vector32", "polarity": 0}
    ],
    "ConditionalSetBool": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
        {"id": "Bool3", "polarity": 0},
        {"id": "Bool1", "polarity": 1}
    ],
    "ConditionalSetSurvivalEmote": [
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 0},
        {"id": "SurvivalEmote2", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 1}
    ],
    "ConditionalSetSurvivalState": [
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "SurvivalState2", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 1}
    ],
    "ConstructSurvivalProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "String2", "polarity": 0}
    ],
    "GetVariable": [
        {"id": "Any1", "polarity": 1}
    ],
    "IsNull": [
        {"id": "Any1", "polarity": 0},
        {"id": "Bool1", "polarity": 1}
    ],
    "Keypress": [
        {"id": "Bool1", "polarity": 1}
    ],
    "Region": [],
    "Relay": [
        {"id": "Any1", "polarity": 0},
        {"id": "Any1", "polarity": 1}
    ],
    "SetVariable": [
        {"id": "Any1", "polarity": 0}
    ],
    "SurvivalAutoPosition": [
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "SurvivalController": [
        {"id": "Vector31", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 0}
    ],
    "SurvivalEmote": [
        {"id": "SurvivalEmote1", "polarity": 1}
    ],
    "SurvivalGetBool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "SurvivalGetFloat": [
        {"id": "Float1", "polarity": 1}
    ],
    "SurvivalGetTransform": [
        {"id": "Transform1", "polarity": 1}
    ],
    "SurvivalState": [
        {"id": "SurvivalState1", "polarity": 1}
    ],
    "TimePlot": [
        {"id": "String1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},  # optional min graph value (Unity v0.5+)
        {"id": "Float3", "polarity": 0},  # optional max graph value
    ],
    "ModularCarController": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
    ],
    "UniformModularCarProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Color3", "polarity": 0},
        {"id": "String2", "polarity": 0},
    ],
    "Spherecast": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Spherecast1", "polarity": 1},
    ],
    "CarRaycasts": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "HitInfo": [
        {"id": "RaycastHit1", "polarity": 0},
        {"id": "Bool1", "polarity": 1},
        {"id": "Float1", "polarity": 1},
        {"id": "String1", "polarity": 1},
    ],
    "ParkingGetFloat": [{"id": "Float1", "polarity": 1}],
    "ParkingGetBool": [{"id": "Bool1", "polarity": 1}],
    "ParkingGetTransform": [{"id": "Transform1", "polarity": 1}],
    "DemoDerbyGetTransform": [{"id": "Transform1", "polarity": 1}],
    "DemoDerbyGetCar": [
        {"id": "Float1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "GetCarPart": [
        {"id": "Car1", "polarity": 0},
        {"id": "Transform1", "polarity": 1},
        {"id": "Float1", "polarity": 1},
    ],
    "CarInfo": [
        {"id": "Car1", "polarity": 0},
        {"id": "Transform1", "polarity": 1},
        {"id": "Vector31", "polarity": 1},
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool2", "polarity": 1},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 1},
    ],
    "Autosteer": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "Autothrottle": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "GetCarFromTransform": [
        {"id": "Transform1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "CreateFunction": [
        # Return is Any1 polarity In (matches Prefabs/Ports/In/Any - In.prefab on CreateFunction).
        # Param1 is also Any1 but polarity Out — same id, different polarity.
        {"id": "Any1", "polarity": 0},
        {"id": "String1", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "String3", "polarity": 0},
        {"id": "String4", "polarity": 0},
        {"id": "Any1", "polarity": 1},
        {"id": "Any2", "polarity": 1},
        {"id": "Any3", "polarity": 1},
        {"id": "Any4", "polarity": 1},
    ],
    "Function": [
        {"id": "Any1", "polarity": 0},
        {"id": "Any2", "polarity": 0},
        {"id": "Any3", "polarity": 0},
        {"id": "Any4", "polarity": 0},
        {"id": "Any1", "polarity": 1},
    ],
    "SoccerController1": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController2": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController4": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerPlayerSensors1": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors2": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors3": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors4": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "ConstructSoccerProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector33", "polarity": 0},
        {"id": "Vector34", "polarity": 0},
    ],
    "SoccerGetBool": [{"id": "Bool1", "polarity": 1}],
    "SoccerGetFloat": [{"id": "Float1", "polarity": 1}],
    "SoccerGetTransform": [{"id": "Transform1", "polarity": 1}],
    "SoccerGetVector3": [{"id": "Vector31", "polarity": 1}],
    "RacingV2GetFloat": [{"id": "Float1", "polarity": 1}],
    "RacingV2GetBool": [{"id": "Bool1", "polarity": 1}],
    "RacingV2GetCar": [
        {"id": "Float1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "RacingV2GetWaypoint": [
        {"id": "Float1", "polarity": 0},
        {"id": "Waypoint1", "polarity": 1},
    ],
    "RacingV2Waypoint": [
        {"id": "Waypoint1", "polarity": 0},
        {"id": "Transform1", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Float1", "polarity": 1},
    ],
    "ConstructRacingV2Properties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Color3", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "Stat1", "polarity": 0},
        {"id": "Stat2", "polarity": 0},
        {"id": "Stat3", "polarity": 0},
    ],
}

colorNames = Literal[
    "Auburn",
    "Black",
    "Blonde",
    "Blue",
    "Brown",
    "Dark Brown",
    "Dark Green",
    "Green",
    "Hot Pink",
    "Light Blue",
    "Light Grey",
    "Medium Grey",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Tan",
    "White",
    "Yellow",
]
countryNames = Literal[
    "Unknown",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Bermuda",
    "Bohemia",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "DR Congo",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Grok",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Lithuania",
    "Luxembourg",
    "Malaysia",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Netherlands",
    "New Zealand",
    "Niger",
    "Nigera",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Somolia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
