from typing import Literal

# Default node dimensions (width, height) matching Unity prefabs - for full serialization format
NODE_SIZES = {
    "String": (256, 64),
    "Float": (256, 64),
    "Color": (256, 64),
    "Country": (256, 64),
    "Bool": (256, 64),
    "ModularCarController": (192, 160),
    "UniformModularCarProperties": (192, 288),
    "Spherecast": (256, 64),
    "CarRaycasts": (192, 160),
    "HitInfo": (256, 64),
    "ParkingGetFloat": (320, 64),
    "ParkingGetBool": (320, 64),
    "ParkingGetTransform": (320, 64),
    "DemoDerbyGetTransform": (320, 64),
    "DemoDerbyGetCar": (320, 64),
    "GetCarPart": (320, 64),
    "CarInfo": (192, 224),
    "Autosteer": (192, 160),
    "Autothrottle": (192, 160),
    "GetCarFromTransform": (256, 64),
    "ConstructSurvivalProperties": (192, 288),
    "ConstructVector3": (256, 160),
    "CompareFloats": (256, 160),
    "CompareBool": (256, 160),
    "SurvivalGetFloat": (320, 64),
    "SurvivalGetBool": (320, 64),
    "SurvivalState": (256, 64),
    "ConditionalSetSurvivalState": (256, 288),
    "ConditionalSetSurvivalEmote": (256, 288),
    "SurvivalAutoPosition": (256, 64),
    "SurvivalEmote": (256, 64),
    "SurvivalController": (192, 160),
    "Relay": (32, 32),
    "AddFloats": (256, 64),
    "SubtractFloats": (256, 64),
    "MultiplyFloats": (256, 64),
    "DivideFloats": (256, 64),
    "Not": (256, 64),
    "Modulo": (256, 64),
    "Operation": (256, 64),
    "Power": (256, 64),
    "Lerp": (256, 96),
    "GetVariable": (256, 64),
    "SetVariable": (256, 64),
    "IsNull": (256, 64),
    "Region": (256, 224),
    "CreateFunction": (400, 332),
    "Function": (256, 160),
    "SoccerController1": (192, 160),
    "SoccerController2": (192, 160),
    "SoccerController3": (192, 160),
    "SoccerController4": (192, 160),
    "SoccerPlayerSensors1": (192, 224),
    "SoccerPlayerSensors2": (192, 224),
    "SoccerPlayerSensors3": (192, 224),
    "SoccerPlayerSensors4": (192, 224),
    "ConstructSoccerProperties": (192, 224),
    "SoccerGetBool": (320, 64),
    "SoccerGetFloat": (320, 64),
    "SoccerGetTransform": (320, 64),
    "SoccerGetVector3": (320, 64),
    "ConstructTennisProperties": (192, 224),
    "TennisController": (192, 160),
    "TennisGetBool": (320, 64),
    "TennisGetFloat": (320, 64),
    "TennisGetVector3": (320, 64),
    "TennisGetTransform": (320, 64),
    "TennisAutoSwing": (320, 96),
    "TennisAutoMove": (192, 128),
    "TennisAutoAim": (192, 64),
    "RacingV2GetFloat": (320, 64),
    "RacingV2GetBool": (320, 64),
    "RacingV2GetCar": (320, 64),
    "RacingV2GetWaypoint": (320, 64),
    "RacingV2Waypoint": (256, 96),
    "ConstructRacingV2Properties": (192, 320),
    "Stat": (256, 64),
}
DEFAULT_NODE_SIZE = (256, 64)

# Node types that serialize size/color per NodeTypeDataSO (e.g. Region has user-resizable dimensions)
SERIALIZE_SIZE_DELTA_NODES = {"Region", "CreateFunction"}
SERIALIZE_COLOR_NODES = {"Region"}

# Default colors matching Unity (RGBA 0-1)
DEFAULT_NODE_COLOR = {"r": 0.21960784494876862, "g": 0.21960784494876862, "b": 0.21960784494876862, "a": 1}
DEFAULT_CONNECTION_COLOR = {"r": 0.98, "g": 0.94, "b": 0.84, "a": 1}
CAP_COLOR = {"r": 1, "g": 0.81, "b": 0.3, "a": 1}

# Dropdown / selection modifier options for nodes whose `modifier` field
# represents a Unity dropdown selection. Keys are node IDs.
# Values are ordered display labels (index = dropdown value).
#
# Used by `_normalize_modifier` in lib.py to:
# - accept int index (wrapped) or string label
# - emit a stringified index (default) or the label text for
#   nodes listed in DROPDOWN_MODIFIER_AS_LABEL
DROPDOWN_OPTIONS: dict[str, tuple[str, ...]] = {
    # Parking simulation
    "ParkingGetTransform": ("Self", "Target Parking Stall"),
    "ParkingGetBool": (
        "Is Partially in Target Parking Stall",
        "Is Fully in Target Parking Stall",
    ),
    "ParkingGetFloat": (
        "Speed",
        "Distance to Stall (based on pathfinding)",
        "Target Stall Width",
        "Target Stall Depth",
        "Current Level",
        "Fail Count",
        "Current Simulation Time",
        "Max Simulation Time",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
        "Signed Speed (forward +, reverse −)",
    ),
    # RacingV2 simulation
    "RacingV2GetFloat": (
        "Speed",
        "Signed Speed (forward +, reverse −)",
        "Index of next waypoint",
        "Index of previous waypoint",
        "Waypoint count",
        "Current race rank",
        "Number of competitors",
        "Distance to next waypoint",
        "Distance to previous waypoint",
        "Current lap time",
        "Best lap time",
        "Total race time",
        "Current lap",
        "Total laps",
        "Current Simulation Time",
        "Max Simulation Time",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
    ),
    "RacingV2GetBool": (
        "Is Grounded",
        "Is Disabled",
        "Simulation started",
    ),
    "RacingV2GetCar": (
        "By index",
        "By rank",
        "Self",
        "Nearest car",
        "Furthest car",
        "Lowest health car",
        "Highest health car",
        "Last damaged car",
        "Nearest active car",
        "Furthest active car",
        "Nearest disabled car",
        "Furthest disabled car",
        "Nearest car with disabled steering",
        "Furthest car with disabled steering",
        "Nearest AI-Authored",
        "Lowest health AI-Authored",
        "Highest health AI-Authored",
        "Nearest Human-Authored",
        "Lowest health Human-Authored",
        "Highest health Human-Authored",
        "Highest ranked car",
        "Lowest ranked car",
        "Nearest ranked car (rank neighbor)",
        "Highest ranked (not immobilized)",
        "Highest ranked (immobilized)",
        "Lowest ranked (not immobilized)",
        "Lowest ranked (immobilized)",
    ),
    "RacingV2GetWaypoint": (
        "Next waypoint",
        "Previous waypoint",
        "By index",
        "Start waypoint",
    ),
    "RacingV2Waypoint": (
        "Center",
        "Left",
        "Right",
        "Nearest point",
    ),
    # Soccer simulation
    "SoccerGetBool": (
        "Team Has Ball",
        "Opponent Has Ball",
        "Is Ball Loose",
        "Team Player 1 Has Ball",
        "Team Player 2 Has Ball",
        "Team Player 3 Has Ball",
        "Team Player 4 Has Ball",
        "Opponent Player 1 Has Ball",
        "Opponent Player 2 Has Ball",
        "Opponent Player 3 Has Ball",
        "Opponent Player 4 Has Ball",
        "Is Ball Nearby Team Player 1",
        "Is Ball Nearby Team Player 2",
        "Is Ball Nearby Team Player 3",
        "Is Ball Nearby Team Player 4",
        "Is Ball Nearby Opponent Player 1",
        "Is Ball Nearby Opponent Player 2",
        "Is Ball Nearby Opponent Player 3",
        "Is Ball Nearby Opponent Player 4",
        "Is Team Player 1 Closest Teammate to Ball",
        "Is Team Player 2 Closest Teammate to Ball",
        "Is Team Player 3 Closest Teammate to Ball",
        "Is Team Player 4 Closest Teammate to Ball",
        "Is Opponent Player 1 Closest Opponent to Ball",
        "Is Opponent Player 2 Closest Opponent to Ball",
        "Is Opponent Player 3 Closest Opponent to Ball",
        "Is Opponent Player 4 Closest Opponent to Ball",
        "Is Team Player 1 Open",
        "Is Team Player 2 Open",
        "Is Team Player 3 Open",
        "Is Team Player 4 Open",
        "Is Opponent Player 1 Open",
        "Is Opponent Player 2 Open",
        "Is Opponent Player 3 Open",
        "Is Opponent Player 4 Open",
        "Is Kickoff",
        "Is Team Kicking off",
        "Is Opponent Kicking off",
        "Team Is Winning",
        "Opponent Is Winning",
        "Team Scored Last Point",
        "Opponent Scored Last Point",
        "Ball On Team Side",
        "Ball On Opponent Side",
        "Is Ball Headed Towards Team Goal",
        "Is Ball Headed Towards Opponent Goal",
        "Is Home Team",
        "Is Away Team",
        "Is Active Graph",
    ),
    "SoccerGetFloat": (
        "Team Score",
        "Opponent Score",
        "Team Shots",
        "Opponent Shots",
        "Team Possession %",
        "Opponent Possession %",
        "Team Attacking %",
        "Opponent Attacking %",
        "Ball Speed",
        "Player Interact Radius",
        "Ball Carrier Stamina",
        "Ball Carrier Shot Charge",
        "Teammate 1 Shot Charge",
        "Teammate 2 Shot Charge",
        "Teammate 3 Shot Charge",
        "Teammate 4 Shot Charge",
        "Field Width",
        "Field Depth",
        "Kickoff Circle Radius",
        "Goal Width",
        "Goal Height",
        "Team Player 1 Stamina",
        "Team Player 2 Stamina",
        "Team Player 3 Stamina",
        "Team Player 4 Stamina",
        "Distance from Team Player 1 to nearest Opponent",
        "Distance from Team Player 2 to nearest Opponent",
        "Distance from Team Player 3 to nearest Opponent",
        "Distance from Team Player 4 to nearest Opponent",
        "Opponent Player 1 Stamina",
        "Opponent Player 2 Stamina",
        "Opponent Player 3 Stamina",
        "Opponent Player 4 Stamina",
        "Opponent Nearest Teammate Player 1 Stamina",
        "Opponent Nearest Teammate Player 2 Stamina",
        "Opponent Nearest Teammate Player 3 Stamina",
        "Opponent Nearest Teammate Player 4 Stamina",
        "Stamina of last defending opponent",
        "Current Simulation Time",
        "Max Simulation Time",
        "Simulation Time Remaining",
        "Delta Time",
        "Fixed Delta Time",
        "Pi",
    ),
    "SoccerGetTransform": (
        "Ball",
        "Team Player 1",
        "Team Player 2",
        "Team Player 3",
        "Team Player 4",
        "Opponent Player 1",
        "Opponent Player 2",
        "Opponent Player 3",
        "Opponent Player 4",
        "Teammate Nearest Team Player 1",
        "Teammate Nearest Team Player 2",
        "Teammate Nearest Team Player 3",
        "Teammate Nearest Team Player 4",
        "Opponent Nearest Team Player 1",
        "Opponent Nearest Team Player 2",
        "Opponent Nearest Team Player 3",
        "Opponent Nearest Team Player 4",
        "Team Goal Center",
        "Team Goal Left Post",
        "Team Goal Right Post",
        "Opponent Goal Center",
        "Opponent Goal Left Post",
        "Opponent Goal Right Post",
        "Opponent Nearest Team Goal",
        "Opponent Nearest Opponent Goal",
        "Teammate Nearest Team Goal",
        "Teammate Nearest Opponent Goal",
    ),
    "SoccerGetVector3": (
        "Ball Velocity",
        "Clear direction from team carrier",
        "Backwards clear direction from team carrier",
        "Clear direction from team carrier (avoid goal lines)",
        "Clear direction from team carrier (avoid sidelines)",
        "Clear direction from team carrier (avoid all walls)",
        "Upper Corner Home Side",
        "Lower Corner Home Side",
        "Upper Midfield",
        "Lower Midfield",
        "Upper Corner Away Side",
        "Lower Corner Away Side",
        "Upper Corner Opposing Side",
        "Lower Corner Opposing Side",
        "Upper Corner Team Side",
        "Lower Corner Team Side",
        "Center Field",
        "Get nearest open teammate",
        "Get furthest open teammate",
        "Get most open teammate",
        "Get nearest open opponent",
        "Get furthest open opponent",
        "Get most open opponent",
        "Direction of clear teammate from Teammate 1",
        "Direction of clear teammate from Teammate 2",
        "Direction of clear teammate from Teammate 3",
        "Direction of clear teammate from Teammate 4",
        "Direction of clear teammate from Opponent 1",
        "Direction of clear teammate from Opponent 2",
        "Direction of clear teammate from Opponent 3",
        "Direction of clear teammate from Opponent 4",
        "Direction of ball from Teammate 1",
        "Direction of ball from Teammate 2",
        "Direction of ball from Teammate 3",
        "Direction of ball from Teammate 4",
        "Direction of ball from Opponent 1",
        "Direction of ball from Opponent 2",
        "Direction of ball from Opponent 3",
        "Direction of ball from Opponent 4",
        "Direction of team goal from Teammate 1",
        "Direction of team goal from Teammate 2",
        "Direction of team goal from Teammate 3",
        "Direction of team goal from Teammate 4",
        "Direction of opponent goal from Teammate 1",
        "Direction of opponent goal from Teammate 2",
        "Direction of opponent goal from Teammate 3",
        "Direction of opponent goal from Teammate 4",
        "Clear direction from Teammate 1",
        "Clear direction from Teammate 2",
        "Clear direction from Teammate 3",
        "Clear direction from Teammate 4",
        "Direction of teammate from Team Player 1",
        "Direction of teammate from Team Player 2",
        "Direction of teammate from Team Player 3",
        "Direction of teammate from Team Player 4",
    ),
    # Tennis simulation
    # Tennis v0.012 labels (live TennisGet*Gate.BuildItems order).
    "TennisGetBool": (
        "Is Playing",
        "Is Home",
        "Is Self Server For Set",
        "Is Opponent Server For Set",
        "Is Serve Phase",
        "Is Self Actively Serving",
        "Is Second Serve",
        "Is Ad Court Serve",
        "Is Ball Playable",
        "Was Last Shot Topspin",
        "Was Last Shot Slice",
        "Was Last Shot Flat",
        "Was Last Shot Lob",
        "Was Last Shot Drop",
        "Was Last Shot Curve Left",
        "Was Last Shot Curve Right",
        "Was Last Shot Trick",
        "Is Self Charging",
        "Is Opponent Charging",
        "Is Self Winning",
        "Is Opponent Winning",
        "Is Tied",
        "Is Deuce",
        "Is Game Point",
        "Is Break Point",
        "Is Match Point",
        "Ball On Self Side",
        "Ball Incoming",
        "Ball In Swing Range",
        "Ball Has Bounced",
        "Must Wait For Bounce",
        "Ball Has Charged Effect",
        "Self Scored Last Point",
        "Opponent Scored Last Point",
        "Self Has Advantage",
    ),
    "TennisGetFloat": (
        "Shot: Topspin",
        "Shot: Slice",
        "Shot: Flat",
        "Shot: Drop",
        "Shot: Lob",
        "Shot: Curve Left",
        "Shot: Curve Right",
        "Shot: Random",
        "Shot: Last Self Shot",
        "Shot: Last Opponent Shot",
        "Shot: Most Used Self Shot",
        "Shot: Most Used Opponent Shot",
        "Shot: Most Scored Self Shot",
        "Shot: Most Scored Opponent Shot",
        "Shot: Ball",
        "Self Swing Charge Pct",
        "Opponent Swing Charge Pct",
        "Self Stamina Pct",
        "Opponent Stamina Pct",
        "Deuce Fatigue",
        "Rally Fatigue",
        "Court Width",
        "Court Depth",
        "Net Height",
        "Ball Speed",
        "Ball Time To Ground",
        "Self Time To Destination",
        "Serve Number",
        "Self Points",
        "Opponent Points",
        "Self Set Score",
        "Opponent Set Score",
        "Self Aces",
        "Opponent Aces",
        "Self Faults",
        "Opponent Faults",
        "Self Charged Shots",
        "Opponent Charged Shots",
    ),
    "TennisGetVector3": (
        "Ball Position",
        "Ball Velocity",
        "Predicted Bounce",
        "Center Of Half",
        "Center Of Back",
        "Serve Stance",
        "Receive Stance",
        "Legal Serve Target",
        "Random Aim Target",
        "Self Average Scoring Location",
        "Opponent Average Scoring Location",
        "Estimated Opponent Shot Location",
        "Trick Drop Modifier",
        "Trick Lob Modifier",
        "Trick Curve Left Modifier",
        "Trick Curve Right Modifier",
        "Camera Forward",
        "Camera Right",
    ),
    "TennisGetTransform": (
        "Self",
        "Opponent",
        "Self Racket Center",
        "Ball",
        "Camera",
    ),
    "TennisAutoSwing": (
        "Normal Only",
        "Prefer Charge",
        "Random",
    ),
    "Keypress": (
        "A",
        "Alpha0",
        "Alpha1",
        "Alpha2",
        "Alpha3",
        "Alpha4",
        "Alpha5",
        "Alpha6",
        "Alpha7",
        "Alpha8",
        "Alpha9",
        "AltGr",
        "Ampersand",
        "Asterisk",
        "At",
        "B",
        "BackQuote",
        "Backslash",
        "Backspace",
        "Break",
        "C",
        "CapsLock",
        "Caret",
        "Clear",
        "Colon",
        "Comma",
        "D",
        "Delete",
        "Dollar",
        "DoubleQuote",
        "DownArrow",
        "E",
        "End",
        "Equals",
        "Escape",
        "Exclaim",
        "F",
        "F1",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F2",
        "F20",
        "F21",
        "F22",
        "F23",
        "F24",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "G",
        "Greater",
        "H",
        "Hash",
        "Help",
        "Home",
        "I",
        "Insert",
        "J",
        "JoystickButton0",
        "K",
        "Keypad0",
        "Keypad1",
        "Keypad2",
        "Keypad3",
        "Keypad4",
        "Keypad5",
        "Keypad6",
        "Keypad7",
        "Keypad8",
        "Keypad9",
        "KeypadDivide",
        "KeypadEnter",
        "KeypadEquals",
        "KeypadMinus",
        "KeypadMultiply",
        "KeypadPeriod",
        "KeypadPlus",
        "L",
        "LeftAlt",
        "LeftArrow",
        "LeftBracket",
        "LeftControl",
        "LeftCurlyBracket",
        "LeftMeta",
        "LeftParen",
        "LeftShift",
        "LeftWindows",
        "Less",
        "M",
        "Menu",
        "Minus",
        "Mouse0",
        "Mouse1",
        "Mouse2",
        "N",
        "None",
        "Numlock",
        "O",
        "P",
        "PageDown",
        "PageUp",
        "Pause",
        "Percent",
        "Period",
        "Pipe",
        "Plus",
        "Print",
        "Q",
        "Question",
        "Quote",
        "R",
        "Return",
        "RightAlt",
        "RightArrow",
        "RightBracket",
        "RightControl",
        "RightCurlyBracket",
        "RightMeta",
        "RightParen",
        "RightShift",
        "RightWindows",
        "S",
        "ScrollLock",
        "Semicolon",
        "Slash",
        "Space",
        "SysReq",
        "T",
        "Tab",
        "Tilde",
        "U",
        "Underscore",
        "UpArrow",
        "V",
        "W",
        "WheelDown",
        "WheelUp",
        "X",
        "Y",
        "Z",
    ),
    "CompareBool": (
        "and",
        "or",
        "equal to",
        "xor",
        "nor",
        "nand",
        "xnor",
    ),
    "CompareFloats": (
        "==",
        "<",
        ">",
        "<=",
        ">=",
    ),
    "Operation": (
        "abs",
        "round",
        "floor",
        "ceil",
        "sin",
        "cos",
        "tan",
        "asin",
        "acos",
        "atan",
        "sqrt",
        "sign",
        "ln",
        "log10",
        "e^",
        "10^",
    ),
    "RelativePosition": (
        "Self",
        "Self + Forward",
        "Self + Backward",
        "Self + Left",
        "Self + Right",
        "Self + Up",
        "Self + Down",
        "Forward",
        "Backward",
        "Left",
        "Right",
        "Up",
        "Down",
        "World",
    ),
    "VolleyballGetBool": (
        "Self Can Jump",
        "Opponent Can Jump",
        "Ball Is Self Side",
    ),
    "VolleyballGetFloat": (
        "Delta time",
        "Fixed delta time",
        "Gravity",
        "Pi",
        "Simulation duration",
        "Team score",
        "Opponent score",
        "Ball touches remaining",
    ),
    "VolleyballGetTransform": (
        "Self",
        "Opponent",
        "Ball",
        "Self Team Spawn",
        "Opponent Team Spawn",
    ),
    "SlimeGetVector3": (
        "Self Position",
        "Self Velocity",
        "Ball Position",
        "Ball Velocity",
        "Opponent Position",
        "Opponent Velocity",
    ),
    "SurvivalGetBool": (
        "Is Carrying Resource",
        "Container has Health",
        "Container Was Attacked",
        "Container Was Stolen From",
        "Self Was Attacked",
    ),
    "SurvivalGetFloat": (
        "Health Percentage",
        "Hunger Percentage",
        "Stamina Percentage",
        "Current Rank",
        "Stored Food Count",
        "Distance to Nearest Player",
        "Distance to Nearest Aggressive Player",
        "Distance to Last Attacker",
        "Distance to Nearest Container",
        "Distance to Nearest Fruit Tree",
        "Player Count Remaining",
        "Current Simulation Time",
        "Max Simulation Time",
        "Simulation Time Remaining",
        "Delta time",
        "Fixed delta time",
        "Pi",
        "Self Gathers",
        "Self Food Consumed",
        "Self Steals",
        "Self Damage Dealt",
        "Self Kills",
        "Self Aggression Level",
        "Available Fruit Count",
        "Player Count Without Stored Food",
        "Average Player Health",
        "Average Player Hunger",
        "Average Player Stamina",
        "Average Player Aggression Level",
        "Total Possible Fruit",
        "Distance Traveled",
    ),
    "SurvivalGetTransform": (
        "Self",
        "Player Last Damaged By",
        "Player Last Attacking (Global)",
        "Player Nearest",
        "Player 2nd Nearest",
        "Player Farthest",
        "Player with Highest Health",
        "Player with Lowest Health",
        "Player with Highest Hunger",
        "Player with Lowest Hunger",
        "Player with Highest Stamina",
        "Player with Lowest Stamina",
        "Player Last Stolen From Self Container",
        "Player Last Stealing (Global)",
        "Player with Highest Score",
        "Player with Lowest Score",
        "Player of Closest Score",
        "Player with Most Aggression",
        "Player with Lowest Aggression",
        "Player Nearest with Aggression",
        "Player Nearest with No Aggression",
        "Player with Most Stored Fruit",
        "Player with Least Stored Fruit",
        "Container Self",
        "Container Closest (excluding self)",
        "Container Farthest (excluding self)",
        "Container of Last Attacker",
        "Container of Last Global Attacker",
        "Container of Most Stored Fruit",
        "Container of Nearest Dead Player",
        "Container of Nearest Dead Player (with Food)",
        "Container of Highest Aggression Player",
        "Container of Lowest Aggression Player",
        "Container of Player with Closest Rank",
        "Fruit Nearest",
        "Fruit Farthest",
        "Fruit Nearest Self Container",
        "Fruit (Random)",
        "Tree Nearest",
    ),
    "SurvivalEmote": (
        "None",
        "Hi",
        "Talk",
        "Bored",
        "Wave",
        "Dance2",
    ),
    "SurvivalState": (
        "Passive",
        "Gather",
        "Eat",
        "Attack",
        "Steal",
        "Dead",
    ),
    "DemoDerbyGetTransform": (
        "Self",
        "Fixed Reference",
        "Random Pathable Waypoint",
    ),
    "DemoDerbyGetCar": (
        "By index",
        "By rank",
        "Self",
        "Nearest car",
        "Furthest car",
        "Lowest health car",
        "Highest health car",
        "Last damaged car",
        "Nearest active car",
        "Furthest active car",
        "Nearest disabled car",
        "Furthest disabled car",
        "Nearest car with disabled steering",
        "Furthest car with disabled steering",
        "Nearest AI-Authored",
        "Lowest health AI-Authored",
        "Highest health AI-Authored",
        "Nearest Human-Authored",
        "Lowest health Human-Authored",
        "Highest health Human-Authored",
        "Highest ranked car",
        "Lowest ranked car",
        "Nearest ranked car (rank neighbor)",
        "Highest ranked (not immobilized)",
        "Highest ranked (immobilized)",
        "Lowest ranked (not immobilized)",
        "Lowest ranked (immobilized)",
    ),
    "GetCarPart": (
        "Average of all parts",
        "Nearest part",
        "Weakest part",
        "Nearest crucial part",
        "WheelFL",
        "WheelFR",
        "WheelRL",
        "WheelRR",
        "AxleFL",
        "AxleFR",
        "AxleRL",
        "AxleRR",
        "Engine",
        "Driveshaft",
        "SuspensionFL",
        "SuspensionFR",
        "SuspensionRL",
        "SuspensionRR",
        "Hood",
        "Trunk",
        "BumperFront",
        "BumperRear",
        "LicensePlateFront",
        "LicensePlateRear",
        "FenderFL",
        "FenderFR",
        "DoorL",
        "DoorR",
        "DoorRL",
        "DoorRR",
        "TurnSignalFL",
        "TurnSignalFR",
        "HeadlightL",
        "HeadlightR",
        "TaillightL",
        "TaillightR",
        "WindshieldWipers",
    ),
}

outputs = {
    "AddVector3": "Vector3",
    "AddFloats": float,
    "Bool": bool,
    "ClampFloat": float,
    "Color": float,
    "UniformModularCarProperties": None,
    "ModularCarController": None,
    "ConstructVector3": "Vector3",
    "CompareBool": bool,
    "CompareFloats": bool,
    "ConditionalSetFloatV2": float,
    "ConditionalSetVector3": "Vector3",
    "ConstructSlimeProperties": None,
    "SlimeController": None,
    "Spherecast": "Spherecast",
    "CarRaycasts": "RaycastHit",
    "HitInfo": "Any",
    "Country": "Country",
    "CrossProduct": "Vector3",
    "Debug": None,
    "DebugDrawLine": None,
    "DebugDrawDisc": None,
    "Distance": float,
    "DivideFloats": float,
    "DotProduct": float,
    "Float": float,
    "VolleyballGetBool": bool,
    "VolleyballGetFloat": float,
    "VolleyballGetTransform": "Transform",
    "SlimeGetVector3": "Vector3",
    "Magnitude": float,
    "Modulo": float,
    "MultiplyFloats": float,
    "Not": bool,
    "Normalize": "Vector3",
    "Operation": float,
    "Power": float,
    "Lerp": float,
    "RelativePosition": "Vector3",
    "RandomFloat": float,
    "ScaleVector3": "Vector3",
    "Vector3Split": float,
    "Stat": "Stat",
    "String": str,
    "SubtractFloats": float,
    "SubtractVector3": "Vector3",
    "ConditionalSetBool": bool,
    "ConditionalSetSurvivalEmote": "SurvivalEmote",
    "ConditionalSetSurvivalState": "SurvivalState",
    "ConstructSurvivalProperties": None,
    "GetVariable": "Any",
    "IsNull": bool,
    "Keypress": bool,
    "Region": None,
    "Relay": "Any",
    "SetVariable": None,
    "SurvivalAutoPosition": "Vector3",
    "SurvivalController": None,
    "SurvivalEmote": "SurvivalEmote",
    "SurvivalGetBool": bool,
    "SurvivalGetFloat": float,
    "SurvivalGetTransform": "Transform",
    "SurvivalState": "SurvivalState",
    "TimePlot": None,
    "ParkingGetFloat": float,
    "ParkingGetBool": bool,
    "ParkingGetTransform": "Transform",
    "DemoDerbyGetTransform": "Transform",
    "DemoDerbyGetCar": "Car",
    "GetCarPart": "Transform",
    "CarInfo": "Vector3",
    "Autosteer": float,
    "Autothrottle": float,
    "GetCarFromTransform": "Car",
    "CreateFunction": "Any",
    "Function": "Any",
    "SoccerController1": None,
    "SoccerController2": None,
    "SoccerController3": None,
    "SoccerController4": None,
    "SoccerPlayerSensors1": "RaycastHit",
    "SoccerPlayerSensors2": "RaycastHit",
    "SoccerPlayerSensors3": "RaycastHit",
    "SoccerPlayerSensors4": "RaycastHit",
    "ConstructSoccerProperties": None,
    "SoccerGetBool": bool,
    "SoccerGetFloat": float,
    "SoccerGetTransform": "Transform",
    "SoccerGetVector3": "Vector3",
    "ConstructTennisProperties": None,
    "TennisController": None,
    "TennisGetBool": bool,
    "TennisGetFloat": float,
    "TennisGetVector3": "Vector3",
    "TennisGetTransform": "Transform",
    "TennisAutoSwing": bool,
    "TennisAutoMove": "Vector3",
    "TennisAutoAim": "Vector3",
    "RacingV2GetFloat": float,
    "RacingV2GetBool": bool,
    "RacingV2GetCar": "Car",
    "RacingV2GetWaypoint": "Waypoint",
    "RacingV2Waypoint": "Vector3",
    "ConstructRacingV2Properties": None,
}

ports = {
    "AddVector3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "AddFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Bool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "ClampFloat": [
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Color": [
        {"id": "Color1", "polarity": 1}
    ],
    "ConstructVector3": [
        {"id": "Vector31", "polarity": 1},
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "CompareBool": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool2", "polarity": 0},
        {"id": "Bool1", "polarity": 0}
    ],
    "CompareFloats": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "ConditionalSetFloatV2": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Bool1", "polarity": 0}
    ],
    "ConditionalSetVector3": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "ConstructSlimeProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Stat1", "polarity": 0},
        {"id": "Stat2", "polarity": 0},
        {"id": "Stat3", "polarity": 0}
    ],
    "SlimeController": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Vector31", "polarity": 0}
    ],
    "Country": [
        {"id": "Country1", "polarity": 1}
    ],
    "CrossProduct": [
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector3", "polarity": 1}
    ],
    "Debug": [
        {"id": "Any1", "polarity": 0}
    ],
    "DebugDrawLine": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Color1", "polarity": 0}
    ],
    "DebugDrawDisc": [
        {"id": "Float1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Float2", "polarity": 0}
    ],
    "Distance": [
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Vector31", "polarity": 0}
    ],
    "DivideFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "DotProduct": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "Float": [
        {"id": "Float1", "polarity": 1}
    ],
    "VolleyballGetBool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "VolleyballGetFloat": [
        {"id": "Float1", "polarity": 1}
    ],
    "VolleyballGetTransform": [
        {"id": "Transform1", "polarity": 1}
    ],
    "SlimeGetVector3": [
        {"id": "Vector31", "polarity": 1}
    ],
    "Magnitude": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "Modulo": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "MultiplyFloats": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "Not": [
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool1", "polarity": 0}
    ],
    "Normalize": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "Operation": [
        {"id": "Float1", "polarity": 1},
        {"id": "Float1", "polarity": 0}
    ],
    "Power": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "Lerp": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "RelativePosition": [
        {"id": "Transform1", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "RandomFloat": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 0}
    ],
    "ScaleVector3": [
        {"id": "Float1", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Vector31", "polarity": 0}
    ],
    "Vector3Split": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 1},
        {"id": "Float3", "polarity": 1}
    ],
    "Stat": [
        {"id": "Stat1", "polarity": 1}
    ],
    "String": [
        {"id": "String1", "polarity": 1}
    ],
    "SubtractFloats": [
        {"id": "Float2", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1}
    ],
    "SubtractVector3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Vector32", "polarity": 0}
    ],
    "ConditionalSetBool": [
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
        {"id": "Bool3", "polarity": 0},
        {"id": "Bool1", "polarity": 1}
    ],
    "ConditionalSetSurvivalEmote": [
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 0},
        {"id": "SurvivalEmote2", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 1}
    ],
    "ConditionalSetSurvivalState": [
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "SurvivalState2", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 1}
    ],
    "ConstructSurvivalProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "String2", "polarity": 0}
    ],
    "GetVariable": [
        {"id": "Any1", "polarity": 1}
    ],
    "IsNull": [
        {"id": "Any1", "polarity": 0},
        {"id": "Bool1", "polarity": 1}
    ],
    "Keypress": [
        {"id": "Bool1", "polarity": 1}
    ],
    "Region": [],
    "Relay": [
        {"id": "Any1", "polarity": 0},
        {"id": "Any1", "polarity": 1}
    ],
    "SetVariable": [
        {"id": "Any1", "polarity": 0}
    ],
    "SurvivalAutoPosition": [
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "Vector31", "polarity": 1}
    ],
    "SurvivalController": [
        {"id": "Vector31", "polarity": 0},
        {"id": "SurvivalState1", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "SurvivalEmote1", "polarity": 0}
    ],
    "SurvivalEmote": [
        {"id": "SurvivalEmote1", "polarity": 1}
    ],
    "SurvivalGetBool": [
        {"id": "Bool1", "polarity": 1}
    ],
    "SurvivalGetFloat": [
        {"id": "Float1", "polarity": 1}
    ],
    "SurvivalGetTransform": [
        {"id": "Transform1", "polarity": 1}
    ],
    "SurvivalState": [
        {"id": "SurvivalState1", "polarity": 1}
    ],
    "TimePlot": [
        {"id": "String1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "Float1", "polarity": 0}
    ],
    "ModularCarController": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
    ],
    "UniformModularCarProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Color3", "polarity": 0},
        {"id": "String2", "polarity": 0},
    ],
    "Spherecast": [
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Spherecast1", "polarity": 1},
    ],
    "CarRaycasts": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "HitInfo": [
        {"id": "RaycastHit1", "polarity": 0},
        {"id": "Bool1", "polarity": 1},
        {"id": "Float1", "polarity": 1},
        {"id": "String1", "polarity": 1},
    ],
    "ParkingGetFloat": [{"id": "Float1", "polarity": 1}],
    "ParkingGetBool": [{"id": "Bool1", "polarity": 1}],
    "ParkingGetTransform": [{"id": "Transform1", "polarity": 1}],
    "DemoDerbyGetTransform": [{"id": "Transform1", "polarity": 1}],
    "DemoDerbyGetCar": [
        {"id": "Float1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "GetCarPart": [
        {"id": "Car1", "polarity": 0},
        {"id": "Transform1", "polarity": 1},
        {"id": "Float1", "polarity": 1},
    ],
    "CarInfo": [
        {"id": "Car1", "polarity": 0},
        {"id": "Transform1", "polarity": 1},
        {"id": "Vector31", "polarity": 1},
        {"id": "Bool1", "polarity": 1},
        {"id": "Bool2", "polarity": 1},
        {"id": "Float1", "polarity": 1},
        {"id": "Float2", "polarity": 1},
    ],
    "Autosteer": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "Autothrottle": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float1", "polarity": 1},
    ],
    "GetCarFromTransform": [
        {"id": "Transform1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "CreateFunction": [
        # Return is Any1 polarity In (matches Prefabs/Ports/In/Any - In.prefab on CreateFunction).
        # Param1 is also Any1 but polarity Out — same id, different polarity.
        {"id": "Any1", "polarity": 0},
        {"id": "String1", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "String3", "polarity": 0},
        {"id": "String4", "polarity": 0},
        {"id": "Any1", "polarity": 1},
        {"id": "Any2", "polarity": 1},
        {"id": "Any3", "polarity": 1},
        {"id": "Any4", "polarity": 1},
    ],
    "Function": [
        {"id": "Any1", "polarity": 0},
        {"id": "Any2", "polarity": 0},
        {"id": "Any3", "polarity": 0},
        {"id": "Any4", "polarity": 0},
        {"id": "Any1", "polarity": 1},
    ],
    "SoccerController1": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController2": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController3": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerController4": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "SoccerPlayerSensors1": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors2": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors3": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "SoccerPlayerSensors4": [
        {"id": "Spherecast1", "polarity": 0},
        {"id": "RaycastHit1", "polarity": 1},
        {"id": "RaycastHit2", "polarity": 1},
        {"id": "RaycastHit3", "polarity": 1},
        {"id": "RaycastHit4", "polarity": 1},
        {"id": "RaycastHit5", "polarity": 1},
        {"id": "RaycastHit6", "polarity": 1},
        {"id": "RaycastHit7", "polarity": 1},
        {"id": "RaycastHit8", "polarity": 1},
    ],
    "ConstructSoccerProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector33", "polarity": 0},
        {"id": "Vector34", "polarity": 0},
    ],
    "SoccerGetBool": [{"id": "Bool1", "polarity": 1}],
    "SoccerGetFloat": [{"id": "Float1", "polarity": 1}],
    "SoccerGetTransform": [{"id": "Transform1", "polarity": 1}],
    "SoccerGetVector3": [{"id": "Vector31", "polarity": 1}],
    "ConstructTennisProperties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float2", "polarity": 0},
    ],
    "TennisController": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Bool1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Bool2", "polarity": 0},
    ],
    "TennisGetBool": [{"id": "Bool1", "polarity": 1}],
    "TennisGetFloat": [{"id": "Float1", "polarity": 1}],
    "TennisGetVector3": [{"id": "Vector31", "polarity": 1}],
    "TennisGetTransform": [{"id": "Transform1", "polarity": 1}],
    "TennisAutoSwing": [
        {"id": "Float1", "polarity": 0},
        {"id": "Bool1", "polarity": 1},
        {"id": "Float1", "polarity": 1},
    ],
    "TennisAutoMove": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector32", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
    ],
    "TennisAutoAim": [
        {"id": "Vector31", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
    ],
    "RacingV2GetFloat": [{"id": "Float1", "polarity": 1}],
    "RacingV2GetBool": [{"id": "Bool1", "polarity": 1}],
    "RacingV2GetCar": [
        {"id": "Float1", "polarity": 0},
        {"id": "Car1", "polarity": 1},
    ],
    "RacingV2GetWaypoint": [
        {"id": "Float1", "polarity": 0},
        {"id": "Waypoint1", "polarity": 1},
    ],
    "RacingV2Waypoint": [
        {"id": "Waypoint1", "polarity": 0},
        {"id": "Transform1", "polarity": 0},
        {"id": "Vector31", "polarity": 1},
        {"id": "Float1", "polarity": 1},
    ],
    "ConstructRacingV2Properties": [
        {"id": "String1", "polarity": 0},
        {"id": "Country1", "polarity": 0},
        {"id": "Color1", "polarity": 0},
        {"id": "Float1", "polarity": 0},
        {"id": "Float2", "polarity": 0},
        {"id": "Color2", "polarity": 0},
        {"id": "Float3", "polarity": 0},
        {"id": "Color3", "polarity": 0},
        {"id": "String2", "polarity": 0},
        {"id": "Stat1", "polarity": 0},
        {"id": "Stat2", "polarity": 0},
        {"id": "Stat3", "polarity": 0},
    ],
}

colorNames = Literal[
    "Auburn",
    "Black",
    "Blonde",
    "Blue",
    "Brown",
    "Dark Brown",
    "Dark Green",
    "Green",
    "Hot Pink",
    "Light Blue",
    "Light Grey",
    "Medium Grey",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Tan",
    "White",
    "Yellow",
]
countryNames = Literal[
    "Unknown",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Bermuda",
    "Bohemia",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "DR Congo",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Grok",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Lithuania",
    "Luxembourg",
    "Malaysia",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Netherlands",
    "New Zealand",
    "Niger",
    "Nigera",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Somolia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

# Label-as-modifier nodes (Unity matches option text, not a numeric index).
DROPDOWN_OPTIONS["Color"] = colorNames.__args__
DROPDOWN_OPTIONS["Country"] = countryNames.__args__

DROPDOWN_MODIFIER_AS_LABEL = frozenset(
    {
        "Keypress",
        "Color",
        "Country",
        "SurvivalEmote",
        "SurvivalState",
        "TennisAutoSwing",
        "TennisGetTransform",
        "TennisGetBool",
        "TennisGetFloat",
        "TennisGetVector3",
    }
)

# Legacy tennis labels → current Unity `BuildItems` text. Keys are casefolded.
# Matches `TennisGet*Gate.LabelAliases`. v0.012 renamed serve/time/last-shot
# options; aliases keep older spellings load-safe.
DROPDOWN_ALIASES: dict[str, dict[str, str]] = {
    "TennisGetBool": {
        "i am serving": "Is Self Server For Set",
        "is server": "Is Self Server For Set",
        "self is server": "Is Self Server For Set",
        "is self server": "Is Self Server For Set",
        "is self server for set": "Is Self Server For Set",
        "opponent is server": "Is Opponent Server For Set",
        "is opponent server": "Is Opponent Server For Set",
        "is opponent server for set": "Is Opponent Server For Set",
        "is any team serving": "Is Serve Phase",
        "is serving": "Is Self Actively Serving",
        "self is serving": "Is Self Actively Serving",
        "is self serving": "Is Self Actively Serving",
        "is self actively serving": "Is Self Actively Serving",
        "ball on my side": "Ball On Self Side",
        "can hit": "Is Ball Playable",
        "can swing": "Is Ball Playable",
        "ball is playable": "Is Ball Playable",
        "is ball playable": "Is Ball Playable",
        "ball is lob": "Was Last Shot Lob",
        "is ball lob": "Was Last Shot Lob",
        "ball is drop": "Was Last Shot Drop",
        "is ball drop": "Was Last Shot Drop",
        "ball has topspin": "Was Last Shot Topspin",
        "ball has backspin": "Was Last Shot Slice",
        "is ball nearby": "Ball In Swing Range",
        "ball in swing range": "Ball In Swing Range",
        "does ball have charged effects": "Ball Has Charged Effect",
        "is self charging shot": "Is Self Charging",
        "self is charging": "Is Self Charging",
        "is self charging": "Is Self Charging",
        "is opponent charging shot": "Is Opponent Charging",
        "opponent is charging": "Is Opponent Charging",
        "is winning": "Is Self Winning",
        "self is winning": "Is Self Winning",
        "opponent is winning": "Is Opponent Winning",
        "has advantage": "Self Has Advantage",
    },
    "TennisGetFloat": {
        "shot topspin": "Shot: Topspin",
        "shot slice": "Shot: Slice",
        "shot flat": "Shot: Flat",
        "shot drop": "Shot: Drop",
        "shot lob": "Shot: Lob",
        "shot trick": "Shot: Lob",
        "shot: trick": "Shot: Lob",
        "shot curve left": "Shot: Curve Left",
        "shot curve right": "Shot: Curve Right",
        "random shot": "Shot: Random",
        "self last shot type": "Shot: Last Self Shot",
        "opponent last shot type": "Shot: Last Opponent Shot",
        "self most used shot type": "Shot: Most Used Self Shot",
        "opponent most used shot type": "Shot: Most Used Opponent Shot",
        "self most scored shot type": "Shot: Most Scored Self Shot",
        "opponent most scored shot type": "Shot: Most Scored Opponent Shot",
        "ball shot type": "Shot: Ball",
        "current shot effect applied to ball": "Shot: Ball",
        "self current swing charge pct": "Self Swing Charge Pct",
        "opponent current swing charge pct": "Opponent Swing Charge Pct",
        "est time ball to ground": "Ball Time To Ground",
        "time ball to ground": "Ball Time To Ground",
        "ball time to ground": "Ball Time To Ground",
        "est time to destination": "Self Time To Destination",
        "time to destination": "Self Time To Destination",
        "self time to destination": "Self Time To Destination",
        "current serve number": "Serve Number",
        "serve number": "Serve Number",
    },
    "TennisGetVector3": {
        "trick shot (dropshot) modifier": "Trick Drop Modifier",
        "trick shot (lob) modifier": "Trick Lob Modifier",
        "trick shot (curve left) modifier": "Trick Curve Left Modifier",
        "trick shot (curve right) modifier": "Trick Curve Right Modifier",
    },
    "TennisGetTransform": {
        "racket center": "Self Racket Center",
    },
}
